from django.conf import settings

USERPROFILES_REGISTRATION_FORM = getattr(
    settings, 'USERPROFILES_REGISTRATION_FORM', 'userprofiles.forms.RegistrationForm')

USERPROFILES_USE_PROFILE = getattr(
    settings, 'USERPROFILES_USE_PROFILE', False)

USERPROFILES_USE_PROFILE_VIEW = getattr(
    settings, 'USERPROFILES_USE_PROFILE_VIEW', False)

USERPROFILES_INLINE_PROFILE_ADMIN = getattr(
    settings, 'USERPROFILES_INLINE_PROFILE_ADMIN', False)

USERPROFILES_USE_ACCOUNT_VERIFICATION = getattr(
    settings, 'USERPROFILES_USE_ACCOUNT_VERIFICATION', False)

USERPROFILES_ACCOUNT_VERIFICATION_DAYS = getattr(
    settings, 'USERPROFILES_ACCOUNT_VERIFICATION_DAYS', 7)

USERPROFILES_DOUBLE_CHECK_EMAIL = getattr(
    settings, 'USERPROFILES_DOUBLE_CHECK_EMAIL', False)

USERPROFILES_CHECK_UNIQUE_EMAIL = getattr(
    settings, 'USERPROFILES_CHECK_UNIQUE_EMAIL', False)

USERPROFILES_DOUBLE_CHECK_PASSWORD = getattr(
    settings, 'USERPROFILES_DOUBLE_CHECK_PASSWORD', False)

USERPROFILES_REGISTRATION_FULLNAME = getattr(
    settings, 'USERPROFILES_REGISTRATION_FULLNAME', False)

